### ISSUE TITLE
[BUG] Cannot use Stimulus Values if controller identifier has more than one word

### ISSUE THREAD

**Issue by leminh0796** [YummYume/bun-stimulus-plugin#17]
### Bug description

My bun config:
![image](https://github.com/user-attachments/assets/847645d7-473d-400f-8dc5-9dfb33ae183a)
Controllers load:
![image](https://github.com/user-attachments/assets/ee38026b-86ce-40f7-8025-7c743b0a347e)

I am using ViewComponent with Rails & Hotwire. For example:
![image](https://github.com/user-attachments/assets/6c4af8ec-54e3-4de4-b35e-10f7c48cfbca)
In the controller file:
![image](https://github.com/user-attachments/assets/fa675c9f-bfd5-4ccd-9233-b4428753e960)
In view file:
![image](https://github.com/user-attachments/assets/06569752-92b8-4329-8e30-91f37e352575)

So the identifier is `global--alert_component`
The controller connected just fine but the problem is when it renders to HTML the data value fields become `data-global--alert-component-dismiss-after-value` and Stimulus doesn't understand it.
So I think there is an issue with the controller name when we keep the underscore:
`data-controller="global--alert_component"`
Maybe we should replace all `_` with `-` (follow [the Stimulus convention](https://stimulus.hotwired.dev/reference/controllers#identifiers))

### Bun version

1.1.34

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by leminh0796** [comment]
I've made a [PR](https://github.com/YummYume/bun-stimulus-plugin/pull/18)

**Comment by YummYume** [comment]
I released a new version with the appropriate changes, tell me if anything else is needed.
