### ISSUE TITLE
[FEATURE] Ability to register stimulus controllers using containing folder as identifier

### ISSUE THREAD

**Issue by curreta** [YummYume/bun-stimulus-plugin#7]
### Feature description

I was installing ViewComponent into my Rails application and found your plugin very helpful.

A popular implementation of ViewComponent is this package:
https://github.com/palkan/view_component-contrib

Part of the implementation is to use [sidecar files within a folder](https://github.com/palkan/view_component-contrib#using-with-stimulusjs). As a result the stimulus controllers are called controller.js instead of foobar_controller.js

I propose adding a boolean option to use-directory-as-identifier when registering the stimulus controller instead of the filename.

I hardcoded this into my application, and it works for my purpose, and might be helpful to others if adapted into this plugin as an option.

edit: not fully working code below

```js
 // Parse all the controllers in the given path and handle nested controllers
            const parseControllers = (controllersPath: string, prefix: string = '') => {
                const controllersFromPath = getControllersFromPath(controllersPath);

                for (const controller of controllersFromPath) {
                    const controllerPath = join(controllersPath, controller);
                    const controllerStats = statSync(controllerPath);

                    // Name of the controller without the suffix and with directory separators
                    const controllerName = `${prefix}${controller.replace(options.controllerSuffix, '')}`;

                    if (controllerStats.isDirectory()) {
                        // Recursively parse the controllers
                        parseControllers(controllerPath, `${controllerName}${options.directorySeparator}`);
                    } else {
                        // Controller name should be unique, so we'll add a number to the end of it
                        const uniqueControllerName = `${parseControllerName(controllerName)}${(i += 1)}`;

                        // Import the controller
                        contents += `import ${uniqueControllerName} from '${join(
                            args.path,
                            ...prefix.split(options.directorySeparator),
                            controller,
                        )}';`;

                        // Convert path into a controller identifier:
                        //   example/index.js -> example
                        //   nav/user_info/index.js -> nav--user-info
                        const identifier = dirname(controllerPath)
                            .replace(args.path, '')
                            .replace(new RegExp(`^${sep}`), '') // remove leading directory separator
                            .split(sep)
                            .join(options.directorySeparator)
                            .replace(/^-|-$/g, ''); // remove leading and trailing separators

                        definitions.push({
                            identifier,
                            name: uniqueControllerName,
                        });
                    }
                }
            };
            ```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by YummYume** [comment]
Hi @curreta, thanks for opening this issue !

So as I understand it, it would go like this : 

- Controller names are now registered with the folder's name rather than the file
- Only `index.(ts|js)` (?) files would be accounted for
- Top level files (e.g. `controllers/index.ts`) with import `stimulus:controllers`, would be completely ignored as a result

I'm not sure about how this would be implemented in the options, but I'm thinking about 2 possibilities : 

```ts
type BunStimulusPluginOptions = {
  // other options...
  directoryIdentifier: {
    enabled: boolean;
    indexFileName: RegExp;
  }
}
```

Which would result in the following for your case : 

```ts
bunStimulusPlugin({
  directoryIdentifier: {
    enabled: true,
    indexFileName: /index.(js|ts)$/gi, // This would probably be the default option anyway
  }
})
```

Or instead, a single option that would allow you to capture any group in the controller's path using RegExp, which could allow you to completely customize the name of the controllers. However, that would probably be harder to implement and be confusing to users, so the first option seems better.

Another question is, what happens with the `controllerSuffix` option? Would it get totally ignored, or would it still be used, even for folders ?

**Comment by curreta** [comment]
👋 Hi @YummYume,

Thanks for considering this feature! I've outlined a more detailed concept below, which includes the `useDirectoryAsIdentifier` option and a configurable pattern for included files. 

### Proposed Feature

1. **`useDirectoryAsIdentifier`**: When set to `true`, the directory path is used to form the Stimulus controller's identifier.

2. **`includedFiles`**: A pattern (regular expression) to specify which files should be treated as controllers.

### Configuration Example

```javascript
bunStimulusPlugin({
  useDirectoryAsIdentifier: true,
  includedFiles: /controller.js$/, // This pattern can be adjusted as needed
})
```

### Identifier Formation Examples

Based on the above configuration, here are five examples of how different folder structures would translate into identifiers:

1. **Simple Controller**
   - Folder Structure: `controllers/navbar/controller.js`
   - Identifier: `navbar`

2. **Nested Controller**
   - Folder Structure: `controllers/navbar/menu/controller.js`
   - Identifier: `navbar--menu`

3. **Deeply Nested Controller**
   - Folder Structure: `controllers/navbar/menu/items/controller.js`
   - Identifier: `navbar--menu--items`

4. **Multiple Controllers in Nested Structure**
   - Folder Structures:
     - `controllers/navbar/controller.js`
     - `controllers/navbar/menu/controller.js`
   - Identifiers:
     - `navbar`
     - `navbar--menu`

5. **Varied Naming Convention**
   - Folder Structures:
     - `controllers/settings/controller.js`
     - `controllers/settings/user_preferences/index.js`
   - Identifiers (assuming `includedFiles` pattern includes `index.js`):
     - `settings`
     - `settings--user_preferences`

**Comment by curreta** [comment]
Some untested LLM output to help move things along.

### Pseudo-Code Example

The pseudo-code example outlines the conceptual flow of the process:

```plaintext
1. Set up plugin configuration with `useDirectoryAsIdentifier` and `includedFiles` options.

2. For each file in the controllers directory:
   a. Check if the file matches the `includedFiles` pattern. If not, skip to the next file.
   b. Extract the relative directory path of the file.
   c. If `useDirectoryAsIdentifier` is true:
      - Form the identifier by joining the directory names using the `directorySeparator`.
   d. Register the controller with the formed identifier.

3. Continue until all matching files in the directory have been processed.
```

### Actual Code Example

Here's an example with actual code, demonstrating how you might implement this in JavaScript:

```javascript
import { resolve, join, sep } from 'path';
import { Glob } from "bun";

export type BunStimulusPluginOptions = {
    useDirectoryAsIdentifier: boolean;
    includedFiles: RegExp;
    directorySeparator: string;
};

// Default plugin options
const defaultOptions: BunStimulusPluginOptions = {
    useDirectoryAsIdentifier: true,
    includedFiles: /controller.js$/,
    directorySeparator: '--',
};

export const bunStimulusPlugin = (
    bunStimulusPluginOptions: Partial<BunStimulusPluginOptions> = defaultOptions,
): BunPlugin => ({
    name: 'bun-stimulus-plugin',
    async setup(build) {
        const options = { ...defaultOptions, ...bunStimulusPluginOptions };

        build.onLoad({ filter: /.*/, namespace }, async (args) => {
            const glob = new Glob("**/*.js"); // Adjust glob pattern as needed
            const definitions: ControllerDefinition[] = [];
            let contents = '';

            for await (const file of glob.scan(args.path)) {
                if (!file.match(options.includedFiles)) continue;

                const relativePath = file.replace(args.path, '').replace(/^\//, '');
                const pathSegments = relativePath.split('/').slice(0, -1); // Exclude the file name
                const identifier = options.useDirectoryAsIdentifier
                    ? pathSegments.join(options.directorySeparator)
                    : pathSegments.pop();

                const uniqueControllerName = `controller${definitions.length + 1}`;
                contents += `import ${uniqueControllerName} from '${resolve(args.path, file)}';`;
                definitions.push({ identifier, name: uniqueControllerName });
            }

            contents += `export default [${definitions.map(definition => `{identifier: '${definition.identifier}', controllerConstructor: ${definition.name}}`).join(',')}];`;
            return {
                contents,
                loader: 'js',
            };
        });
    },
});
```

In this code example, the `bunStimulusPlugin` function sets up the plugin with the specified options. It then scans through the specified directory, filtering files based on the `includedFiles` pattern. For each file that matches, it forms an identifier based on the directory structure if `useDirectoryAsIdentifier` is true, and adds each controller to a list of definitions. Finally, it exports these definitions, which can be used to register the Stimulus controllers.

**Comment by YummYume** [comment]
Hi :wave: Thanks for adding precise examples of what is excepted (I'll use them for tests).

So, thinking a bit more about it and experimenting locally, I found out that, based on the current options, I should keep using pattern matching instead of booleans to enable things. This is mostly so it would allow covering most use cases in the future, like the one you have here, that I never anticipated.

Using Glob matching also sounds like a good idea, but I was afraid it wouldn't be enough for matching some suffixes, which is why I decided to go with Regex instead. However, these new options could definitely use globs for easy matching of directories.

Here is another idea I found interesting, which would add the possibility to basically match anything, and even mix together file and directory based controllers : 

```ts
{
  // other options...
  /**
   * The suffix of the controller files to load. Will be removed from the controller's name.
   * Defaults to `(-|_)controller.(js|ts|jsx|tsx)$`.
   *
   * @since 1.0.0
   */
  controllerSuffix: RegExp | null;
  /**
   * The glob pattern to use to identify files that should be registered with their file name.
   * Set to `null` to disable this feature. Defaults to `/**\/*`.
   *
   * @since 1.1.0
   */
  fileIdentifier: string | null;
  /**
   * The glob pattern to use to identify files that should be registered with their parent directory name.
   * Set to `null` to disable this feature. Defaults to `null`.
   *
   * @since 1.1.0
   */
  directoryIdentifier: string | null;
}
```

So for your use case, you would use : 

```ts
{
  controllerSuffix: null, // this would be null because you don't want to remove anything from your file names
  fileIdentifier: null, // this would disable file based identifiers
  directoryIdentifier: '/**/{index,controller}.js' // this would match any file within a directory named index.js or controller.js
}
```

**Comment by YummYume** [comment]
I just released a new version of the plugin, which now includes the ability to register directory-based controllers using globs. For your use case, the usage would be : 

```ts
{
  fileIdentifier: null, // disable file based identifiers
  directoryIdentifier: '**/{index,controller}.js' // this would match any file within a directory named index.js or controller.js
}
```
